sp500 = [
    'AAPL', 'MSFT', 'AMZN', 'GOOGL', 'GOOG', 'FB', 'TSLA', 'BRK.B', 'NVDA', 'JPM',
    'JNJ', 'V', 'PYPL', 'PG', 'UNH', 'MA', 'DIS', 'HD', 'BAC', 'CMCSA', 'INTC',
    'ADBE', 'CRM', 'VZ', 'NFLX', 'KO', 'MRK', 'T', 'PEP', 'PFE', 'WMT', 'ABT',
    'CSCO', 'XOM', 'ABBV', 'NKE', 'AVGO', 'ORCL', 'CVX', 'LLY', 'MCD', 'ACN',
    'QCOM', 'TXN', 'COST', 'HON', 'NEE', 'MDT', 'UNP', 'PM', 'AMGN', 'LIN',
    'BMY', 'DHR', 'MMM', 'IBM', 'BA', 'UPS', 'LOW', 'SBUX', 'GS', 'CAT', 'GE',
    'AMT', 'TMO', 'RTX', 'MS', 'CVS', 'AMD', 'NOW', 'INTU', 'ISRG', 'SCHW',
    'TJX', 'BLK', 'FIS', 'GILD', 'LMT', 'MDLZ', 'MO', 'ADP', 'TFC', 'BKNG',
    'ZTS', 'SYK', 'CI', 'PLD', 'SPGI', 'CB', 'CCI', 'AXP', 'CHTR', 'CME', 'ANTM',
    'PNC', 'DUK', 'USB', 'MMC', 'D', 'BDX', 'ITW', 'CSX', 'VRTX', 'FISV', 'SO',
    'ADSK', 'NSC', 'PGR', 'EOG', 'CL', 'MU', 'EL', 'ICE', 'HUM', 'ADI', 'ILMN',
    'APD', 'REGN', 'COF', 'BIIB', 'KMB', 'CTSH', 'TRV', 'DD', 'BSX', 'MET',
    'WBA', 'SHW', 'AON', 'NEM', 'ETN', 'EW', 'WM', 'EMR', 'ROST', 'AEP',
    'WM', 'EMR', 'ROST', 'AEP', 'DE', 'ROP', 'LRCX', 'AFL', 'COP', 'CMG', 'MCO',
    'MNST', 'GD', 'IDXX', 'EBAY', 'DLR', 'ALGN', 'SRE', 'F', 'CNC', 'SLB',
    'JCI', 'PSA', 'KLAC', 'ALXN', 'CTAS', 'SNPS', 'CDNS', 'INFO', 'MSCI', 'WEC',
    'ALL', 'WELL', 'HCA', 'SYY', 'IQV', 'VRTX', 'PAYX', 'PPG', 'DG', 'ORLY',
    'APH', 'AME', 'EXC', 'GIS', 'YUM', 'ECL', 'FLT', 'CMI', 'OXY', 'PRU', 'ADT',
    'ZBH', 'PSX', 'BAX', 'VLO', 'SWK', 'RMD', 'CMS', 'PPL', 'TGT', 'OKE',
    'VRSK', 'SPG', 'MAR', 'ES', 'LHX', 'PCAR', 'ED', 'WLTW', 'XLNX', 'PEG',
    'PH', 'LEN', 'VFC', 'HPQ', 'MCHP', 'AMP', 'SJM', 'BBY', 'TT', 'ROK',
    'AEE', 'FE', 'FAST', 'MTD', 'WY', 'DAL', 'AVB', 'MKC', 'A', 'LYB', 'KR',
    'NTRS', 'AWK', 'ETR', 'STZ', 'GLW', 'TEL', 'CCL', 'STT', 'SWKS', 'TDG',
    'UHS', 'CARR', 'KMI', 'BLL', 'ADM', 'DTE', 'VIAC', 'CTVA', 'FTI', 'KEYS',
    'LVS', 'KSU', 'LH', 'AKAM', 'ODFL', 'FITB', 'DFS', 'HLT', 'SBAC', 'ESS',
    'WAT', 'HSY', 'BKR', 'MCK', 'HPE', 'AJG', 'MKTX', 'ANSS', 'CPRT', 'AZO',
    'NUE', 'RCL', 'DOV', 'DVN', 'NOC', 'VMC', 'XYL', 'HIG', 'VTRS', 'EXPE',
    'DLTR', 'SIVB', 'GRMN', 'AAP', 'ABC', 'DOW', 'CTLT', 'KHC', 'CE', 'CFG',
    'CAG', 'HRL', 'IEX', 'TTWO', 'ANET', 'JKHY', 'QRVO', 'SYF', 'TFX', 'IR',
    'WST', 'RSG', 'FRC', 'MAS', 'DISH', 'CAH', 'K', 'BXP', 'PXD', 'ZBRA',
    'CBOE', 'STE', 'ATO', 'WAB', 'PKG', 'VTRS', 'MHK', 'NVR', 'POOL', 'FBHS',
    'BR', 'IP', 'SNA', 'EQR', 'WRB', 'LW', 'IT', 'EFX', 'CHD', 'J', 'BIO',
    'RJF', 'TRMB', 'FANG', 'L', 'INCY', 'ARE', 'KEY', 'FOXA', 'GPC', 'NDAQ',
    'AVY', 'ALLE', 'LUMN', 'TXT', 'FMC', 'RE', 'GL', 'PEAK', 'CTXS', 'WHR',
    'PAYC', 'IPG', 'MPWR', 'HSIC', 'TFX', 'CDW', 'WYNN', 'HWM', 'CNP', 'HBI',
    'IFF', 'LYV', 'CMS', 'BEN', 'CMS', 'TROW', 'HST', 'UDR', 'VAR', 'NLOK',
    'CINF', 'PFG', 'PNW', 'EMN', 'WU', 'EXPD', 'COG', 'NWL', 'NI', 'EVRG',
    'NWSA', 'PNR', 'XRAY', 'HFC', 'OGN', 'AES', 'CPB', 'IRM', 'UNM', 'HII',
    'PBCT', 'SEE', 'RL', 'APA', 'NLSN', 'FFIV', 'AIZ', 'ATO', 'NOV', 'LEG',
    'MOS', 'LB', 'DISCK', 'REG', 'ALK', 'FLIR', 'FLS', 'IVZ', 'PWR', 'SLG',
    'PBCT', 'DXC', 'LNC', 'VNO', 'FOX', 'ROL', 'DISCA', 'HFC', 'AMCR', 'UAA',
    'TPR', 'UA', 'BWA', 'JNPR', 'FRT', 'PRGO', 'HRB', 'IPGP', 'XRX', 'MRO',
    'HAL', 'KIM', 'ALK', 'FLIR', 'FLS', 'IVZ', 'PWR', 'SLG', 'PBCT', 'DXC',
    'LNC', 'VNO', 'FOX', 'ROL', 'DISCA', 'HFC', 'AMCR', 'UAA', 'TPR', 'UA',
    'BWA', 'JNPR', 'FRT', 'PRGO', 'HRB', 'IPGP', 'XRX', 'MRO', 'HAL', 'KIM'
]